### ISSUE TITLE
Comunicaciones TP 3

### ISSUE THREAD

**Issue by JuanCruzMz** [costanzoabril/TP_SO_i3_Equipo110#1]

**Comment by JuanCruzMz** [comment]
Listoo

**Comment by JuanCruzMz** [comment]
Perdón la demora, pero después de no se cuantas horas de sufrimiento terminé
... mi primera parte

**Comment by RobertaGabor** [comment]
holaa, peron este finde no estuve en casa. Ahi subi mi parte!

**Comment by RobertaGabor** [comment]
PERON ta bien

**Comment by RobertaGabor** [comment]
modifique la branch tuya juan, y aparece el commit

**Comment by RobertaGabor** [comment]
use $ git checkout --track origin/Muñoz para generar el branch de forma local

**Comment by JuanCruzMz** [comment]
Cómo? Generar de forma local?

**Comment by RobertaGabor** [comment]
claro,o que me pasaba esque cuando hacia checkout me mostraba donde tenia que decir (main) osea el branch en vez de muñoz me decia el commit tipo 21uiu34 ahre, entonces una migo me dijo que cuando abra la branch en mi compu lo baje localmente con track y de ahi edite y pushee

**Comment by RobertaGabor** [comment]
cuando me aparecio Muñoz (el nombre de tu branch) ahi directo ya se habia creado de forma local

**Comment by costanzoabril** [comment]
holaa, perdon por tardar, ya hice hasta el punto 6

**Comment by costanzoabril** [comment]
ah lo del ifconfig no lo puse porque no entiendo que es ni de que consola sacarlo, si saben diganme porque tambien lo tienen que poner ustedes

**Comment by JuanCruzMz** [comment]
Listo el punto 7

**Comment by JuanCruzMz** [comment]
Lo del "ifconfig" (que en Windows es "ipconfig") es escribir "ipconfig" en la consola de Git, copiar y pegar

**Comment by costanzoabril** [comment]
aaaaah, con razón, ya lo agregué

**Comment by RobertaGabor** [comment]
listooo, ya hice el siguiente!

**Comment by costanzoabril** [comment]
ya termine lo mioo

**Comment by JuanCruzMz** [comment]
Listo lo mío también

**Comment by RobertaGabor** [comment]
genial lo mio donee, ( ͡❛ ▿ ͡❛)

**Comment by RobertaGabor** [comment]
abrill, juan abrio un nuevo repo para la interaccion 4 y ahi creo un issue!
